apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-service
  labels:
    app: hash-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-service
  template:
    metadata:
      labels:
        app: hash-service
    spec:
      containers:
        - name: hash-service
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/hash-service:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
