apiVersion: v1
kind: Service
metadata:
  name: hash-service
  labels:
    app: hash-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hash-service
